export enum CaloriesCalculatorAction {
    SET_PRODUCTS_LIST = 'SET_PRODUCTS_LIST',
    SET_MEALS = 'SET_MEALS',
    ADD_MEAL = 'ADD_MEAL',
    REMOVE_MEAL = 'REMOVE_MEAL',
    ADD_PRODUCT = 'ADD_PRODUCT',
    REMOVE_PRODUCT = 'REMOVE_PRODUCT',
    SET_USER = 'SET_USER',
    SET_ERROR = 'SET_ERROR',
}